name: floor_generator
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the dev dependency.
version: 1.4.2
homepage: https://pinchbv.github.io/floor/
repository: https://github.com/pinchbv/floor
issue_tracker: https://github.com/pinchbv/floor/issues
publish_to: none

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  analyzer: ^8.4.0
  code_builder: ^4.11.0
  floor_annotation:
    path: ../floor_annotation
  source_gen: ^4.0.2
  strings: ^4.0.1