name: floor_generator
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the dev dependency.
version: 1.4.2
homepage: https://pinchbv.github.io/floor/
repository: https://github.com/pinchbv/floor
issue_tracker: https://github.com/pinchbv/floor/issues
publish_to: none

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  analyzer: ^6.4.1
  build: ^2.5.4
  # build: ^3.0.0
  build_config: ^1.1.2
  code_builder: ^4.10.1
  collection: ^1.19.1
  floor_annotation:
    path: ../floor_annotation
  meta:
  source_gen: ^2.0.0
  # source_gen: ^3.0.0
  strings: ^4.0.0
